-- Execute este script inteiro no Supabase: SQL Editor > New query > Run.
create table if not exists usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null,
  role text not null default 'user' check (role in ('admin','user')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  preco numeric(10,2) not null default 0,
  quantidade integer not null default 0,
  validade date not null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists entradas_produtos (
  id bigint generated by default as identity primary key,
  produto_id bigint references produtos(id) on delete cascade,
  produto_nome text,
  quantidade integer not null,
  usuario_id uuid references usuarios(id) on delete set null,
  usuario_nome text,
  observacao text,
  data_entrada timestamptz not null default now()
);

create table if not exists saidas_produtos (
  id bigint generated by default as identity primary key,
  produto_id bigint references produtos(id) on delete cascade,
  produto_nome text,
  quantidade integer not null,
  usuario_id uuid references usuarios(id) on delete set null,
  usuario_nome text,
  observacao text,
  data_saida timestamptz not null default now()
);

create table if not exists historico (
  id bigint generated by default as identity primary key,
  usuario_id uuid references usuarios(id) on delete set null,
  usuario_nome text,
  produto_id bigint references produtos(id) on delete set null,
  produto_nome text,
  acao text not null,
  descricao text,
  data_acao timestamptz not null default now()
);

alter table usuarios enable row level security;
alter table produtos enable row level security;
alter table entradas_produtos enable row level security;
alter table saidas_produtos enable row level security;
alter table historico enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public as $$
  select exists(select 1 from usuarios where id = auth.uid() and role = 'admin');
$$;

create policy "usuarios_select" on usuarios for select to authenticated using (true);
create policy "usuarios_insert_self_or_admin" on usuarios for insert to authenticated
  with check (auth.uid() = id or public.is_admin());
create policy "usuarios_update" on usuarios for update to authenticated
  using (auth.uid() = id or public.is_admin());
create policy "usuarios_delete_admin" on usuarios for delete to authenticated
  using (public.is_admin());

create policy "produtos_all" on produtos for all to authenticated using (true) with check (true);
create policy "entradas_all" on entradas_produtos for all to authenticated using (true) with check (true);
create policy "saidas_all" on saidas_produtos for all to authenticated using (true) with check (true);
create policy "historico_all" on historico for all to authenticated using (true) with check (true);
